# Google Cloud Build config for building a docker container with
# physionet DeID. Sample usage:
#  gcloud builds submit . --config=cloudbuild.yaml \
#  --project=${PROJECT:?} --substitutions="_PHYSIONET_VERSION=1.1"

steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://physionet.org/physiotools/sources/deid/deid-${_PHYSIONET_VERSION}.tar.gz']
- name: 'ubuntu'
  args: ['tar', '-xzf', 'deid-${_PHYSIONET_VERSION}.tar.gz']
- name: 'ubuntu'
  args: ['mkdir', 'docker-build']
- name: 'ubuntu'
  args: ['cp', 'Dockerfile', 'docker-build/']
- name: 'ubuntu'
  args: ['cp', 'deid-${_PHYSIONET_VERSION}/deid.pl', 'docker-build/']
- name: 'ubuntu'
  args: ['cp', '-r', 'deid-${_PHYSIONET_VERSION}/lists', 'docker-build/']
- name: 'ubuntu'
  args: ['cp', '-r', 'deid-${_PHYSIONET_VERSION}/dict', 'docker-build/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/physionet:latest', 'docker-build/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/physionet:deid-${_PHYSIONET_VERSION}', 'docker-build/']

images:
  - 'gcr.io/${PROJECT_ID}/physionet:latest'
