# Google Cloud Build config for building a docker container with
# MIST. Sample usage:
#  gcloud builds submit . --config=cloudbuild.yaml \
#  --project=${PROJECTNAME?}

steps:
- name: 'ubuntu'
  args: ['mkdir', 'docker-build']
- name: 'ubuntu'
  args: ['cp', 'Dockerfile', 'docker-build/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/mist:latest', 'docker-build/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/mist:${BUILD_ID}', 'docker-build/']

images:
  - 'gcr.io/${PROJECT_ID}/mist:latest'
  - 'gcr.io/${PROJECT_ID}/mist:${BUILD_ID}'
